# GitHub Pages Configuration
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

# Site Settings
title: Ajdin Dervišić
description: Informatik Student | HTL Bulme Graz | Developer
logo: /assets/images/profile-placeholder.jpg

# Personal Info
author:
  name: Ajdin Dervišić
  email: ajdin.dervisic@bulme.at
  github: DerAjdin

# Theme Settings
show_downloads: false